# Generated by Django 5.0.6 on 2024-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
