# Generated by Django 5.0.6 on 2024-06-22 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_menu_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="vote",
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="menu",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
