# Generated by Django 5.0.6 on 2024-06-22 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_menu_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
